import java.util.*;
import java.lang.*;
public class ComplexDemo {
	public ComplexDemo() {

	}
	public static void main(String[] args) {
		Complex complexNumber1 = null, complexNumber2 = null, complexNum = null;
		Complex_Object complexObject1 = null, complexObject2 = null, complexObjectNum = null;
		Complex_Generic<Integer> complexGeneric1 = null, complexGeneric2 = null;
		Complex_Generic<Double> complexGeneric3 = null, complexGeneric4 = null;
		Complex_Generic<? extends Number> complexGenericNum = null;
		double val = 0;
		System.out.println("<--------------------Complex with integers---------------------->\n");
		int intReal1 = 0, intImaginary1 = 0, intReal2 = 0, intImaginary2 = 0;
		Scanner scanner = new Scanner(System.in);
		System.out.println("Enter 1st complex number's real part : ");
		intReal1 = scanner.nextInt();
		System.out.println("Enter 1st complex number's imaginary part : ");
		intImaginary1 = scanner.nextInt();
		System.out.println("Enter 2nd complex number's real part : ");
		intReal2 = scanner.nextInt();
		System.out.println("Enter 2nd complex number's imaginary part : ");
		intImaginary2 = scanner.nextInt();
		complexNumber1 = new Complex(intReal1,intImaginary1);
		complexNumber2 = new Complex(intReal2,intImaginary2);
		System.out.print("Sum of the complex numbers is : ");
		Complex num = null;
		complexNum = complexNumber1.add(complexNumber2);
		complexNum.display();
		System.out.print("Difference of the complex numbers is : ");
		complexNum = complexNumber1.subtract(complexNumber2);
		complexNum.display();
		System.out.print("Absolute value of the complex number 1 is : ");
		val = complexNumber1.absolute();
		System.out.println(val);
		System.out.print("Conjugate value of the complex number 1 is : ");
		complexNum = complexNumber1.conjugate();
		complexNum.display();
		System.out.print("Product value of the complex numbers is : ");
		complexNum = complexNumber1.multiply(complexNumber2);
		complexNum.display();
		System.out.println("\n<--------------------Complex with objects---------------------->\n");
		double doubleReal1 = 0, doubleImaginary1 = 0, doubleReal2 = 0, doubleImaginary2 = 0;
		float floatReal1 = 0, floatImaginary1 = 0, floatReal2 = 0, floatImaginary2 = 0;
		System.out.println("\n____Integer output____\n");
		System.out.println("Enter 1st complex number's real part : ");
		intReal1 = scanner.nextInt();
		System.out.println("Enter 1st complex number's imaginary part : ");
		intImaginary1 = scanner.nextInt();
		System.out.println("Enter 2nd complex number's real part : ");
		intReal2 = scanner.nextInt();
		System.out.println("Enter 2nd complex number's imaginary part : ");
		intImaginary2 = scanner.nextInt();
		complexObject1 = new Complex_Object(intReal1,intImaginary1);
		complexObject2 = new Complex_Object(intReal2,intImaginary2);
		System.out.print("Sum of the complex numbers is : ");
		complexObjectNum = complexObject1.add(complexObject2);
		complexObjectNum.display();
		System.out.print("Difference of the complex numbers is : ");
		complexObjectNum = complexObject1.subtract(complexObject2);
		complexObjectNum.display();
		System.out.print("Absolute value of the complex number 1 is : ");
		val = complexObject1.absolute();
		System.out.println(val);
		System.out.print("Conjugate value of the complex number 1 is : ");
		complexObjectNum = complexObject1.conjugate();
		complexObjectNum.display();
		System.out.print("Product value of the complex numbers is : ");
		complexObjectNum = complexObject1.multiply(complexObject2);
		complexObjectNum.display();
		System.out.println("\n____Double output____\n");
		System.out.println("Enter 1st complex number's real part : ");
		doubleReal1 = scanner.nextDouble();
		System.out.println("Enter 1st complex number's imaginary part : ");
		doubleImaginary1 = scanner.nextDouble();
		System.out.println("Enter 2nd complex number's real part : ");
		doubleReal2 = scanner.nextDouble();
		System.out.println("Enter 2nd complex number's imaginary part : ");
		doubleImaginary2 = scanner.nextDouble();
		complexObject1 = new Complex_Object(doubleReal1,doubleImaginary1);
		complexObject2 = new Complex_Object(doubleReal2,doubleImaginary2);
		System.out.print("Sum of the complex numbers is : ");
		complexObjectNum = complexObject1.add(complexObject2);
		complexObjectNum.display();
		System.out.print("Difference of the complex numbers is : ");
		complexObjectNum = complexObject1.subtract(complexObject2);
		complexObjectNum.display();
		System.out.print("Absolute value of the complex number 1 is : ");
		val = complexObject1.absolute();
		System.out.println(val);
		System.out.print("Conjugate value of the complex number 1 is : ");
		complexObjectNum = complexObject1.conjugate();
		complexObjectNum.display();
		System.out.print("Product value of the complex numbers is : ");
		complexObjectNum = complexObject1.multiply(complexObject2);
		complexObjectNum.display();
		System.out.println("\n____Float output____\n");
		System.out.println("Enter 1st complex number's real part : ");
		floatReal1 = scanner.nextFloat();
		System.out.println("Enter 1st complex number's imaginary part : ");
		floatImaginary1 = scanner.nextFloat();
		System.out.println("Enter 2nd complex number's real part : ");
		floatReal2 = scanner.nextFloat();
		System.out.println("Enter 2nd complex number's imaginary part : ");
		floatImaginary2 = scanner.nextFloat();
		complexObject1 = new Complex_Object(floatReal1,floatImaginary1);
		complexObject2 = new Complex_Object(floatReal2,floatImaginary2);
		System.out.print("Sum of the complex numbers is : ");
		complexObjectNum = null;
		complexObjectNum = complexObject1.add(complexObject2);
		complexObjectNum.display();
		System.out.print("Difference of the complex numbers is : ");
		complexObjectNum = complexObject1.subtract(complexObject2);
		complexObjectNum.display();
		System.out.print("Absolute value of the complex number 1 is : ");
		val = complexObject1.absolute();
		System.out.println(val);
		System.out.print("Conjugate value of the complex number 1 is : ");
		complexObjectNum = complexObject1.conjugate();
		complexObjectNum.display();
		System.out.print("Product value of the complex numbers is : ");
		complexObjectNum = complexObject1.multiply(complexObject2);
		complexObjectNum.display();
		System.out.println("\n<--------------------Complex with generics---------------------->\n");
		System.out.println("\n____Integer Output____\n");
		System.out.println("Enter 1st complex number's real part : ");
		intReal1 = scanner.nextInt();
		System.out.println("Enter 1st complex number's imaginary part : ");
		intImaginary1 = scanner.nextInt();
		System.out.println("Enter 2nd complex number's real part : ");
		intReal2 = scanner.nextInt();
		System.out.println("Enter 2nd complex number's imaginary part : ");
		intImaginary2 = scanner.nextInt();
		complexGeneric1 = new Complex_Generic<Integer>(intReal1,intImaginary1);
		complexGeneric2 = new Complex_Generic<Integer>(intReal2,intImaginary2);
		System.out.print("Sum of the complex numbers is : ");
		complexGenericNum = complexGeneric1.add(complexGeneric2);
		complexGenericNum.display();
		System.out.print("Difference of the complex numbers is : ");
		complexGenericNum = complexGeneric1.subtract(complexGeneric2);
		complexGenericNum.display();
		System.out.print("Absolute value of the complex number 1 is : ");
		val = complexGeneric1.absolute();
		System.out.println(val);
		System.out.print("Conjugate value of the complex number 1 is : ");
		complexGenericNum = complexGeneric1.conjugate();
		complexGenericNum.display();
		System.out.print("Product value of the complex numbers is : ");
		complexGenericNum = complexGeneric1.multiply(complexGeneric2);
		complexGenericNum.display();
		System.out.println("\n____Double Output____\n");
		System.out.println("Enter 1st complex number's real part : ");
		doubleReal1 = scanner.nextDouble();
		System.out.println("Enter 1st complex number's imaginary part : ");
		doubleImaginary1 = scanner.nextDouble();
		System.out.println("Enter 2nd complex number's real part : ");
		doubleReal2 = scanner.nextDouble();
		System.out.println("Enter 2nd complex number's imaginary part : ");
		doubleImaginary2 = scanner.nextDouble();
		complexGeneric3 = new Complex_Generic<Double>(doubleReal1,doubleImaginary1);
		complexGeneric4 = new Complex_Generic<Double>(doubleReal2,doubleImaginary2);
		System.out.print("Sum of the complex numbers is : ");
		complexGenericNum = complexGeneric3.add(complexGeneric4);
		complexGenericNum.display();
		System.out.print("Difference of the complex numbers is : ");
		complexGenericNum = complexGeneric3.subtract(complexGeneric4);
		complexGenericNum.display();
		System.out.print("Absolute value of the complex number 1 is : ");
		val = complexGeneric3.absolute();
		System.out.println(val);
		System.out.print("Conjugate value of the complex number 1 is : ");
		complexGenericNum = complexGeneric3.conjugate();
		complexGenericNum.display();
		System.out.print("Product value of the complex numbers is : ");
		complexGenericNum = complexGeneric3.multiply(complexGeneric4);
		complexGenericNum.display();
	}
}